config/routes.rb
Rails.application.routes.draw do
    root 'stickers#index'
    resources :stickers
    resources :categories, only: [:new, :create]
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :stickers
end

app/models/sticker.rb
class Sticker < ActiveRecord::Base
  belongs_to :category
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            redirect_to root_path
        else
            render 'new'
        end   
    end
    
    private
    
    def category_params
        params.require(:category).permit(:name)
    end
end

app/controllers/stickers_controller.rb
class StickersController < ApplicationController
    before_action :find_sticker, only: [:edit, :update, :destroy]
    
    def index
        if params[:category].blank?
            @stickers = Sticker.all.order("created_at DESC")
        else
           @category_id = Category.find_by(name: params[:category]).id
           @stickers = Sticker.where(category_id: @category_id).order("created_at DESC")
        end
    end
    
    def new
        @sticker = Sticker.new
    end
    
    def create
        @sticker = Sticker.new(sticker_params)
        if @sticker.save
            redirect_to root_path    
        else
            render 'new'    
        end
    end
    
    def edit
    end
    
    def update
        if @sticker.update(sticker_params)
            redirect_to root_path    
        else
            render 'edit'
        end
    end
    
    def destroy
        @sticker.destroy
        redirect_to root_path
    end
    
    private
    
    def sticker_params
       params.require(:sticker).permit(:name, :image, :category_id) 
    end
    
    def find_sticker
        @sticker = Sticker.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/stickers_helper.rb
module StickersHelper
end

app/views/categories/new.html.erb
<h1>Add A New Category</h1>


<%= form_for @category do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.submit "Add Category" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stickers/_form.html.erb
<%= form_for @sticker, html: { multipart: true } do |f| %>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose A Category"} %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :image %>
    <%= f.file_field :image %>
    
    <%= f.submit %>
<% end %>

app/views/stickers/_stickers.html.erb
<% @stickers.each do |sticker| %>
    <div class="sticker_unit">
        <%= image_tag sticker.image, alt: "#{sticker.name}" %>
        <p><%= sticker.name %> | <%= sticker.category.name %></p>
        <%= link_to 'Edit', edit_sticker_path(sticker) %>
        <%= link_to 'Delete', sticker_path(sticker), method: :delete, data: {confirm: "Are You Sure?"} %>
    </div>
<% end %>

app/views/stickers/edit.html.erb
<h1>Edit <%= @sticker.name %> Sticker</h1>


<%= render 'form' %>

app/views/stickers/index.html.erb
<h1>What Is Up!</h1>

<%= link_to "All Categories", root_path, remote: true, class: "category_link" %>
<% Category.all.each do |category| %>
    <%= link_to category.name, stickers_path(category: category.name), remote: true, class: "category_link" %>
<% end %>
<br>

<%= link_to "Add Sticker", new_sticker_path %>

<div class="stickers">
    <%= render 'stickers' %>
</div>

<script>
    $('.category_link').on('click', function(){
       $(this).addClass('highlight'); 
    });
</script>

app/views/stickers/index.js.erb
$('.stickers .sticker_unit').remove();
$('.stickers').append('<%= j render("stickers") %>')

app/views/stickers/new.html.erb
<h1>Add a New Sticker</h1>


<%= render 'form' %>